# Generated by Django 4.2.3 on 2023-07-18 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_project_users"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="users",
        ),
    ]
